---

  ######################
  #####   Device   #####
  ######################

device_soapy_str: "hackrf=0,bias_tx=1,if_gain=47,multiply_const=6,buffers=64"


  ######################
  #####   Signal   #####
  ######################

  # 1 = single tone
  # 2 = QPSK (Quadra Phase Key Shift Keying) modulated signal_type
  # 3 = gaussian noise (*)
signal_type: 2

# Note: consider removing this parameter
# in favor of parameters within device_soapy_str.
signal_power: 47


  ######################
  #####   Hopper   #####
  ######################

 # 1 = constant frequency
 # 2 = frequency sweeping
 # 3 = random frequency hopping
   # 3.1 = random frequency hopping with entropy
hopper_mode: 2

# (seconds) time to wait before hopping to the next frequency
hopper_delay_static: 5

hopper_delay_min: 1
hopper_delay_max: 10


  #####################
  ##### Frequency #####
  #####################

frequency_delta: 5
frequency_start: 905
frequency_end: 930




