---

######### DEVICE

soapy_sdr: "hackrf=0,bias_tx=0,if_gain=47,multiply_const=6,buffers=64"

 ## Waveform
    # 1 = single tone
    # 2 = QPSK (Quadra Phase Key Shift Keying) modulated waveform
    # 3 = gaussian noise (*)
waveform: 1

## Power
power: 47



######## HOPPING

 ## FloodAir Type
    # 1 = constant frequency
    # 2 = frequency sweeping
    # 3 = random frequency hopping
hopper: 3

## Hop Time (s)
hop_time: 5

hop_entropy: false
hop_entropy_min: 0.001
hop_entropy_max: 20



####### FREQUENCY

freq_delta: 0.0001
freq_min: 920
freq_max: 920.25




